## Descriptive Statistics
<h3> Calculate Measures of Position using Python </h3>

Calculate the measures of postion such as percentiles, quartiles and z-scores.

In [1]:
import pandas as pd        #for Pandas
import numpy as np         #for calculating percentile
import scipy.stats         #for calculating z-score

In [2]:
df=pd.read_csv("mtcars.csv")

In [3]:
df.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [4]:
df.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

## Percentile

In [5]:
np.percentile(df[['mpg','disp']], 75, axis=0)       #75th percentile of mpg and disp columns

array([ 22.8, 326. ])

In [6]:
np.percentile(df[['mpg','disp']], 50, axis=0) 

array([ 19.2, 196.3])

In [7]:
np.percentile(df[['mpg','disp']], 25, axis=0) 

array([ 15.425, 120.825])

### Calculate the quartile

In [8]:
df[['mpg','disp']].quantile(0.25)

mpg      15.425
disp    120.825
Name: 0.25, dtype: float64

In [9]:
df[['mpg','disp']].quantile(0.50)

mpg      19.2
disp    196.3
Name: 0.5, dtype: float64

In [10]:
df[['mpg','disp']].quantile(0.75)

mpg      22.8
disp    326.0
Name: 0.75, dtype: float64

In [11]:
df.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

### z-score

In [12]:
df["mpg"]

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

In [13]:
from scipy.stats import zscore
zscore(df["mpg"], axis=0)       #z-score of each element in the mpg column

0     0.153299
1     0.153299
2     0.456737
3     0.220730
4    -0.234427
5    -0.335572
6    -0.976163
7     0.726459
8     0.456737
9    -0.150138
10   -0.386145
11   -0.622152
12   -0.470433
13   -0.824444
14   -1.633610
15   -1.633610
16   -0.908732
17    2.075070
18    1.737917
19    2.327934
20    0.237587
21   -0.773871
22   -0.824444
23   -1.144739
24   -0.150138
25    1.215330
26    0.996181
27    1.737917
28   -0.723298
29   -0.065850
30   -0.858159
31    0.220730
Name: mpg, dtype: float64